# fetching the latest node image on alpine linux.
FROM node:alpine As development

#Declaring env 
ENV NODE_ENV development

#Setting up the directory
WORKDIR /todo-app 

#Installing depnedencies
COPY ./package.json /todo-app
RUN npm install

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm start